### ISSUE TITLE
The API field "userAssigendIdentity" not self explaining

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/bluexp-cloud-volumes-ontap#112]
Page: [Set up Cloud Volumes ONTAP to use a customer-managed key in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-set-up-azure-encryption.html)

Hi, 

it is mentioned, that a "userAssignedIdentity" is required for the API call. It would be helpful for the user if the process of finding the ID on Azure (and its prerequisites) could be more explained.

"userAssignedIdentity": " userAssignedIdentityId", [Optional]***

In addition, it would be helpful to provide a link where the [Optional] parameters are listed. 

Thank you.

**Comment by netapp-rlithman** [comment]
Hi @kholger. Thank you for sharing this suggestion with us. 

Do you know the process of finding the ID on Azure (and its prerequisites)?

**Comment by kholger** [comment]
Hi Rachel,

Thanks for your quick answer.
Well, I'm not sure if went the correct path, but it worked for when I created a user assigned managed identiy in the "Managed Identities" section on Azure. Then I assigned the custom role on subscription level to it.
The "userAssignedIdentity" could be found on properties of this new created maanged identity.

In the BlueXP API Call I used then following parameters:

"azureEncryptionParameters": {
              "key": "holger-keyname",
              "vaultName": "holger-KVname",
              "userAssignedIdentity": "/subscriptions/xxx-xxx-xxx-xxx-xxx/resourcegroups/holger-occmtest2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/holgerkvuami"
}

But I am not sure if there is another way without creating such a user assigned managed identity on which level the permissions have to be assigned.

Thanks 
Holger

**Comment by netapp-rlithman** [comment]
Thanks for sharing the steps you tried and further details. I'm going to check with the team and get back to you.

**Comment by kholger** [comment]
Hi, 
Did you already get any feedback from the team?
Thank you

**Comment by netapp-rlithman** [comment]
We are working on the issue with the team.

**Comment by alikulov** [comment]
Hi, any updates on the issue?
I'm also trying to deploy CVO in Azure with encryption and it's still not clear what should be used in userAssignedIdentity parameter.

**Comment by netapp-rlithman** [comment]
Hi Arthur. Thanks for asking about this. It's still a work in progress. I'll share an update soon.

**Comment by netapp-rlithman** [comment]
Hi Arthur. I won't be able to update the documentation until the new year. I have some information that I think can help. Can you email me at rlithman@netapp.com, and I'll send you the information? Thanks.

**Comment by netapp-rlithman** [comment]
It has not. We require information from the engineering team to resolve the issue. Thanks for checking.

**Comment by netapp-rlithman** [comment]
After working with the team, we have incorporated changes to resolve the issue. Thanks! 

Page: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-azure-encryption.html#data-encryption-overview
