### ISSUE TITLE
Change service name to Keystone Subscription services

### ISSUE THREAD

**Issue by netapp-manini** [NetAppDocs/bluexp-cloud-volumes-ontap#182]
Page: [Cloud Volumes ONTAP licensing](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html)

Keystone Flex Subscription has been deprecated as a service term. Please rename all instances in this topic and other instances, as applicable, to Keystone Subscription services.

Also, please change the reference link text to "Learn more about NetApp Keystone".

**Comment by netapp-rlithman** [comment]
Hi Manini. Thank you for pointing this out. We are beginning the process of renaming services for BlueXP and the one you point out is included as a term to rename. @netapp-dbagwell is handling the renaming for Cloud Volumes ONTAP.

**Comment by netapp-manini** [comment]
@netapp-dbagwell , no worries...

When I suggested Keystone Flex Subscriptions >> Keystone Subscriptions, I meant that it should be now mentioned as Keystone Subscriptions, but because my docs had multiple instances, adding "services" could be more appropriate at times. If you think Keystone Subscriptions should suffice, please use that.

I see you made this change: "Learn more about Keystone Flex Subscriptions >> Learn more about NetApp Keystone Subscriptions". I suggested this because this is the product home page for NetApp Keystone, and we do not always use Subscriptions there...

https://www.netapp.com/services/keystone/

**Comment by netapp-dbagwell** [comment]
Hi @netapp-manini. Rather than linking to the primary keystone site, we'd prefer to link to one of these two pages. Do you have a preference? They're based off shared content.

From CVO docs: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html
From digital wallet docs: https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-keystone.html

**Comment by netapp-manini** [comment]
Hi @netapp-dbagwell, I was thinking that users can search for Keystone content within the same repo and find the first link. It would better to add either the digital wallet link or the Keystone core doc link: https://docs.netapp.com/us-en/keystone-staas/index.html 

You can check and add any of these as you deem fit.
