### ISSUE TITLE
We should not need port 53 inbound for CVO HA

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/bluexp-cloud-volumes-ontap#193]
### Page URL

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/reference-networking-azure.html

### Page title

Networking requirements for Cloud Volumes ONTAP in Azure

### Summary

Port 53 is used for DNS, but CVO is not a DNS server so we should only need port 53 outbound, not inbound.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi. Thank you for sharing this feedback. I'm going to check with the technical team and loop you in.

**Comment by netapp-rlithman** [comment]
This issue is a request for enhancement and not a doc issue. Please look for an email from me with information on how to request this enhancement. Thank you.
