### ISSUE TITLE
Update suggestion

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/bluexp-cloud-volumes-ontap#195]
### Page URL

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/reference-limitations.html

### Page title

Known limitations

### Summary

Hi, we added support for S3 protocol in Google Cloud CVO also back in November after initial release in Azure and AWS back in July.

Should we re-phrase this section?
Currently says: "While Cloud Volumes ONTAP supports S3 as an option for scale-out storage _**in some cloud providers**_, BlueXP doesn’t provide any management capabilities for this feature. "

The part from "in some cloud providers" believe is a remaining from we were not supporting it in Google Cloud.

Propose to change to:
"While Cloud Volumes ONTAP supports S3 as an option for scale-out storage, BlueXP doesn’t provide any management capabilities for this feature."

Regards,
Gabriel

**Additional data**
Google Cloud:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html#ontap-s3-license-in-google-cloud
AWS:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html#ontap-s3-license-in-aws
Azure:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html#ontap-s3-license-in-azure

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi Gabriel. We took your suggestion and updated the [Known limitations](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-limitations.html) page. Thanks!
