### ISSUE TITLE
why there is no Health Probe port port (63001-63004) rules in this doc?

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/bluexp-cloud-volumes-ontap#206]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html

### Page title

Networking requirements for Cloud Volumes ONTAP in Azure

### Summary

I can see the health probe port is list under GCP, but why not list in Azure network requirement doc? 
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#requirements-specific-to-ha-pairs

Please add those info in somewhere of the below doc:

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html?q=upgrade#security-group-rules

HA systems have less inbound rules than single node systems because inbound data traffic goes through the Azure Standard Load Balancer. Because of this, traffic from the Load Balancer should be open, as shown in the "AllowAzureLoadBalancerInBound" rule.

Additionally, 4 frontend IPs (FIPs) are configured to migrate on failover events. These frontend IPs live in the load balancer.

Cluster management IP
NodeA data IP (NFS/CIFS)
NodeB data IP (NFS/CIFS)
SVM management IP

azurecvoha::> set diag -confirmations off
azurecvoha::*> debug smdb table network_load_balancer_ui show
node          vserver-name lif-name     probe-port last-probe-time   remove-listener active
------------- ------------ ------------ ---------- ----------------- --------------- ------
azurecvoha-01 azurecvoha   cluster-mgmt 63001      7/6/2023 04:54:01 false           true
azurecvoha-01 svm_azurecvoha
                           data_1       63002      7/6/2023 04:54:01 false           true
azurecvoha-01 svm_azurecvoha
                           svm_azurecvoha_mgmt_lif
                                        63004      7/6/2023 04:54:02 false           true
azurecvoha-02 svm_azurecvoha
                           data_2       63003      7/6/2023 04:54:00 false           true
4 entries were displayed.

azurecvoha::*>

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@Xinwei-Wang, thank you for submitting this feedback. We'll investigate and update the documentation soon.

Thanks again,
Ben

**Comment by netapp-rlithman** [comment]
Hi Xinwei. The team found that this port is already documented on the following page: [Networking requirements for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html#security-group-rules). The priority and name are listed as 65001
AllowAzureLoad BalancerInBound. No changes are required. Thanks.
