### ISSUE TITLE
Document the minimum required permissions needed for an Azure user to follow steps to create add'l data serving SVM 

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/bluexp-cloud-volumes-ontap#209]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in Azure

### Summary

A customer has asked me what the minimum permissions an Azure account would have to have in order to provision resources relating to > 1 data-serving SVM in ONTAP.  This is important as most of the process to do this in Azure is not yet orchestrated by BXP.

* Minimum permissions to allocate additional IP addresses to a NIC
* Minimum permissions to perform Frontend IP configuration steps
* Minimum permissions to perform Health Probes configuration steps
* Minimum permissions to perform Load balancer rules configuration steps

Can that be documented for customer reference?  

Thanks, -Steve

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hi Steve, 

Thank you so much for your feedback. We will review this item with the engineering team and update the documentation appropriately. We will keep you posted when the updated content is published. 

If you have any other feedback, please let us know. 

Thanks again for your help, 

Don Riley

**Comment by wilshields** [comment]
I verified that the Network Contributor role can be used for the Azure tasks to add an IP address to a vnic. If they want to create a custom policy, here is MSFT's official documentation:

[https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface?tabs=azure...](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface?tabs=azure-portal#permissions)

**Comment by netapp-driley** [comment]
I wanted to provide an update for this item. I presented this issue to the engineering team and they are currently evaluating the best strategy on how to present this information in the documentation. Once a clear path forward is decided, the documentation will be updated. Again, I will keep you posted with any further updates. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
The [documentation](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html) has been updated for this item.
