### ISSUE TITLE
What's the difference between these ransomware solutions?

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-cloud-volumes-ontap#213]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-protecting-ransomware.html

### Page title

Improving protection against ransomware

### Summary

The page immediately starts with a task to enable ransomware protection in BlueXP, but then there's another section at the bottom that talks about autonomous ransomware protection, which appears to be an ONTAP feature (but I'm not sure). As a reader, I'm assuming these are two completely different solutions. What's the difference between them? When should I choose one over the other? Can I use both together? If yes, why would I?

It would help if the first solution is covered in a section of it's own, since the second is in its own section on the page.

One other comment about this page: the first and third screenshots on the page are _very_ large. As a guideline, the text in the screenshot should be similar in size to the text on the page. If using SnagIt, the resolution should be around 96dpi.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hi Ben, 

I'll take a look at this and update the topic. If you find anything else, please let me know. 

Thanks, 

Don

**Comment by netapp-driley** [comment]
The latest changes to this [page](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-protecting-ransomware.html#autonomous-ransomware-protection) are now available.
