### ISSUE TITLE
SVM question

### ISSUE THREAD

**Issue by jwallsnetapp** [NetAppDocs/bluexp-cloud-volumes-ontap#219]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

On the licensing page it states the following:
"With capacity-based licensing, the maximum number of Cloud Volumes ONTAP systems is limited to 20 per NetApp account. A system is a Cloud Volumes ONTAP HA pair, a Cloud Volumes ONTAP single node system, or any additional storage VMs that you create. The default storage VM does not count against the limit. This limit applies to all licensing models."

On https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html#storage-vm-limits
It states that there is a 24 SVM limit. 

Is this an error? Or can someone explain the discrepancy? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi. Thank you for letting us know. I need to check with the team. I'll send an email and include you.

**Comment by netapp-driley** [comment]
Updates for the working environment limits is currently in testing. Documentation will be updated once the testing is complete.
