### ISSUE TITLE
Two wrong description about protocols and BlueXP

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/bluexp-cloud-volumes-ontap#223]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-accelerate-data-access.html

### Page title

Accelerate data access with FlexCache volumes

### Summary

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/68621663/96ca2f93-a012-48c9-8256-3a0ffe834694)
Now SMB is supported.

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/68621663/ac9b118f-63ad-4c44-b869-7d4ba2018558)
It is possible to create flexcache relation using BlueXP UI.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi Kan. Thank you for pointing these out to us. We'll let you know when the update is complete.

**Comment by kanitani** [comment]
I am not referring the manual that you mention.
I am trying it.

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/68621663/e39d25df-9e7b-492b-834b-3b9902f3e557)

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/68621663/be0fa051-1e33-49ab-9907-4f427f1f0bf9)

Is this operation still unavailable?

**Comment by kanitani** [comment]
I could create it between On-prems ONTAP and Amazon FSx for NetApp ONTAP.

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/68621663/b96d6385-2fe4-4f8e-b333-e830c3dc50ca)

**Comment by netapp-rlithman** [comment]
You can enable volume caching between two CVO systems in BlueXP just like you did between Amazon FSx and On-Premises ONTAP. 

I'm going to include a link to the new BlueXP volume caching service and add SMB protocol support to the page.

**Comment by netapp-rlithman** [comment]
On the Accelerate data access with FlexCache volumes page, I updated protocol support to include SMB and added a link to BlueXP's volume caching service. Thank you for your helping us keep the docs current, Kan.
