### ISSUE TITLE
Customer requested us to update as much details as we can  for every sinlge version update 

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/bluexp-cloud-volumes-ontap#226]
### Page URL

https://docs.netapp.com/us-en/bluexp-relnotes/whats-new.html

### Page title

Recent changes in BlueXP

### Summary

As the recent BlueXP version , customer depoly CVO but they found S3 connectivity check is must although they are not using S3,
but for the last deploy on Jan, 2023, they didn't met such issue since in the same env. They thought some design changed, I have assisted them resovled issue, but feedbck from them was : Please update every release note as much details as we can , if the above design related to connectivity check during deploying CVO has changed , please also added that info.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. We will keep you posted once the updated documentation is available. 

Thanks again for your help, 

Don Riley

**Comment by netapp-driley** [comment]
Closing the loop on this item. The connectivity check requirement is for enabling data tiering upon creation. This is mentioned under [step 7 of the Launch CVO in Google Cloud topic](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-a-single-node-system-in-google-cloud).
