### ISSUE TITLE
Node-based license stacking

### ISSUE THREAD

**Issue by wilshields** [NetAppDocs/bluexp-cloud-volumes-ontap#227]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html

### Page title

Manage node-based licenses

### Summary

I see where we have how to add capacity-based licenses for CVO. I have customers requesting that we document the process for node-based license stacking as it is apparently done differently.

They added the licenses to the DW and then had to remove them and add them differently. Product should have these steps.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Thanks for letting us know. We'll take it up with the team and get back to you.

**Comment by netapp-manini** [comment]
Pending comments. Closing for now. The IE team will reopen the task when we receive further inputs.
