### ISSUE TITLE
Requesting clarification on statements for single az vs. multi az

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/bluexp-cloud-volumes-ontap#239]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-azure-encryption.html

### Page title

Set up Cloud Volumes ONTAP to use a customer-managed key in Azure

### Summary

For the statements below:

**Azure HA multiple availability zone**
For root, boot, NVRAM, core and data disks, BlueXP uses a disk encryption set, which enables management of encryption keys with managed disks.

**Azure HA single availability zone**
From ONTAP 9.10.1P3, For NVRAM and the core disk, BlueXP uses a [disk encryption set](https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption), which enables management of encryption keys with managed disks. Lower versions will use Microsoft-managed key, instead of the customer-managed key.

1. Why do we not mention root or boot disks for single az like we do for multi az?  Is there really a difference
2. I see that both statements mention 'managed disks' but only multi az mentions data disks.  If a deployment supports managed disks for data in single az deployment for cvo-ha, are they also encrypted using the customer-managed key?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi. Thanks for sharing this feedback. I'll bring it up with the team and get back to you. If you're a NetApper and would like to be included in the discussion, let me know.

**Comment by netapp-rlithman** [comment]
Hi Steve. We updated the page after reviewing the content with the team. Thanks for sharing your feedback.

**Comment by definitelynotsteve** [comment]
Thank you, Rachel!!
