### ISSUE TITLE
please add more info for the optimized charging

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/bluexp-cloud-volumes-ontap#240]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

The customer has a question about the below explanation if the below is being charged?
1.ReadOnly(RO) of Snapmirror DP volume 
2.I/O of Snapmirror sync,resync

DOC:

Optimized
- Charging is based on two cost components: storage and usage (I/O)
**You will not be charged for I/O related to data replication (SnapMirror) or NDMP.**

As I checked from the below info, only user operations are charged:

https://fieldportal.netapp.com/content/1441552?assetComponentId=1444477
Which I/O operations are charged with the Optimized package?
Answer: Only user operations on FlexVolumes are charged. SnapMirror or Snapvault operations are
excluded I/O from charges.

Can you add the above info to the doc?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Thanks for your feedback, Xinwei. I have drafted an update for review by you and the team and shared it in email. I'll follow up with you there.

**Comment by netapp-rlithman** [comment]
The update is live.
