### ISSUE TITLE
Doc changes needed to reflect all types of licenses require Marketplace subscription for CBS to work

### ISSUE THREAD

**Issue by Anilkum1** [NetAppDocs/bluexp-cloud-volumes-ontap#241]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

"Includes unlimited volume backups using BlueXP backup and recovery, but only for Cloud Volumes ONTAP systems that use the Professional package" under the Professional license section no longer holds true as Cloud solution architect team has confirmed that all license types require Marketplace subscription or Backup and Restore license.

Without the proper license or mark place subscription, BlueXP will not allow backups to be enabled.

CDS-7223

Please make the necessary changes.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and make the necessary changes to the documentation. We will keep you posted once the updated documentation is available. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
The latest document changes are now available.

**Comment by netapp-tonacki** [comment]
Hi,  I have updated the licensing topic in the Backup and recovery documentation as well: https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html#use-a-bluexp-backup-and-recovery-paygo-subscription
