### ISSUE TITLE
Need more detailed information about Autonomous Ransomware Protection license and DW

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/bluexp-cloud-volumes-ontap#247]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-protecting-ransomware.html

### Page title

Improving protection against ransomware

### Summary

It is not unclear that ARP capacity license is required for entire CVO capacity, or volume basis.
"Upon purchase of an add-on license and adding it to the Digital Wallet, you can enable ARP on a per volume basis with Cloud Volumes ONTAP." seems just describing ONTAP's functionality, ARP can enable volume basis. Please explain in detail or show exapmples, like if customer use 4TiB CVO capacity, ARP can be activated with 2TiB ARP license or not.

On the other hand, "Support is not available for the use of licensed features without a license." means ARP can be work without license, but license is needed for support, right?  If only ARP license was expired and CVO still have valid license, ARP dones not stop, but license is needed or ARP is stopped?  

3rd, please add information how to show the digital wallet screenshot or put in the entire BlueXP window.  It is difficult to find this window or widgit. 
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/media/screenshot_arp.png

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We review these items and update the documentation accordingly. We will keep you posted once the updated documentation is available. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
The documentation has been updated and published for this issue.
