### ISSUE TITLE
Missing Azure HA Pair with Managed Disks

### ISSUE THREAD

**Issue by pottsrm** [NetAppDocs/bluexp-cloud-volumes-ontap#249]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html

### Page title

Default configuration for Cloud Volumes ONTAP

### Summary

Please include the proper disk configuration requirements for Azure (HA pair)
HA pairs with Managed Disks in a single Availability Zone. Thank you

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. We will keep you posted once the updated documentation is published. 

Thanks again, 

Don Riley

**Comment by netapp-rlithman** [comment]
Hello pottsrm. Azure HA pairs in multiple availability zones are HA pairs with managed disks. I can update the text for the heading so it's clear.

**Comment by netapp-rlithman** [comment]
The page has been updated. Thanks again for your feedback.
