### ISSUE TITLE
Specific Types of Storage Used for CVO

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-cloud-volumes-ontap#250]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html

### Page title

Default configuration for Cloud Volumes ONTAP

### Summary

I'm not sure how much this applies to AWS or GCP but for Azure I've run into this with a customer trying to estimate cost for internal project management.

This page provides a great summary for the storage that is used with the various hyperscalers but doesn't describe the storage used for Tiering.  In Azure for example, elsewhere in the documentation makes reference to blob storage but doesn't specify the type of storage (Block Blob, File Blob, etc?) and when customers are pricing out storage using their internal tools they often will ask what type of storage is being used.  This has led to confusion because when you say blob storage they will ask what kind? Page blob? File Blob? Table Blob?  Also need to specify in the case of Azure that Hot or Cool access can be used.

In addition, although we specify the size and type of disk used, we don't specify the performance configuration.  For example in Azure we P3 Managed disk for boot, P20 for nvram and root disks but we don't mention that in the docs.  I have a customer trying to build an internal spreadsheet with the various SKUs that are going to be used when deploying CVO and need that level of detail so they can price based on their contracted price how much the service will cost them to run.

A bit more detail here would reduce the number of questions we get on how CVO is provisioned within the hyperscaler.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. We will keep you posted once the updated documentation is available. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
Hi - Thanks again for reaching out to us. More information on Data Tiering and Performance can be found through the following in the Cloud Volumes ONTAP documentation: 
- https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html
- https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-performance.html
