### ISSUE TITLE
Feedback on 'Change charging methods'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-cloud-volumes-ontap#260]
### Summary

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#change-charging-methods
Would it be possible to add a link with the steps to get the license file(s) for Customers under section “Update capacity-based license”
The hyperlink could be added in the highlighted section below.
![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/66023260/b0fb73f7-4fb1-4ca5-a61c-1b4a7cd34301)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hi Chanda - Thank you for the feedback. We'll look at this item and update the documentation accordingly. Also, we'll follow via email as needed. If you have any other feedback, please feel free to reach out to us directly. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
The documentation has been updated and now includes a link on how to obtain a system license file.
