### ISSUE TITLE
Please add info about AWS KMS keys rotating

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/bluexp-cloud-volumes-ontap#267]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-aws-key-management.html

### Page title

Manage keys with AWS Key Management Service

### Summary

We have the same info about Key rotation on Azure, but no such info on AWS:

-  Azure:

   https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-azure-encryption.html#key-rotation
   Key rotation
   If you create a new version of your key, Cloud Volumes ONTAP automatically uses the latest key version.

-  AWS:

   https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-aws-key-management.html
   Manage keys with AWS Key Management Service

The customer is checking if they don't need to anything on CVO side if they are using AWS KMS key with automatic rotating ,
As my check it should no anything need them to do on the CVO, but please check and add such info on the doc like the Azure.

https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. We will keep you posted once the updated documentation is available. If you have any other feedback, please let us know.

Thanks again,

Don Riley

**Comment by netapp-driley** [comment]
Hello - For AWS, we have a Set up topic that is similar to [the Azure setup topic](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-azure-encryption.html#data-encryption-overview) you referenced: 

- https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-setting-up-kms.html

The above topic should have all the information the user needs for setting up a customer-managed-key in AWS. Information on automatic rotation is available through the AWS documentation linked in the[ docs.netapp.com topic](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-setting-up-kms.html
).
