### ISSUE TITLE
Lead sentence question

### ISSUE THREAD

**Issue by netapp-rlithman** [NetAppDocs/bluexp-cloud-volumes-ontap#268]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-security-groups.html

### Page title

Security group rules for AWS

### Summary

Hey Ben. I'm looking for good lead examples and came across this lead sentence with grammar errors. 
> You might want to refer to the ports for testing purposes or if you prefer your to use own security groups.

@netapp-bcammett Should I revise the sentence as follows: "You might want to refer to the ports for testing purposes or if you prefer to use your own security groups"?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Yes, sounds great.

**Comment by netapp-bcammett** [comment]
Note that the same issue appears on these pages:

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html#security-group-rules
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#firewall-rules

**Comment by netapp-rlithman** [comment]
Fixed. Thanks! 

#270
