### ISSUE TITLE
BlueXP Capacity Management mode should set to Manual when using WORM

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetAppDocs/bluexp-cloud-volumes-ontap#272]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html

### Page title

WORM storage

### Summary

BlueXP Automatic mode might not work properly with the WORM feature due to the inability to move volumes between data aggregates automatically. BlueXP Capacity Management mode should set to Manual.

https://docs.netapp.com/us-en/ontap/snaplock/move-snaplock-volume-concept.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi Pablo. Thank you for sharing your feedback. The team will review your request and follow up.

**Comment by netapp-driley** [comment]
Hi @pablogarciaarevalo  - Following up on this item, do you know what version of Cloud Volumes ONTAP you were running when capacity management required manual mode for the WORM feature?

**Comment by pablogarciaarevalo** [comment]
Hello @netapp-driley , I think it's regardless the CVO version. Using the BlueXP automatic management feature, one volume could be moved from one aggregate to another aggregate due to some capacity constrains. And the volume movement of a WORM volume doesn't work without enabling the snaplock role to an user
https://docs.netapp.com/us-en/ontap/snaplock/move-snaplock-volume-concept.html#create-a-snaplock-security-administrator-account

**Comment by netapp-driley** [comment]
Following up on this item, the CVO team was able to confirm "cluster admin user that is used in BlueXP does in fact have the required role for moving a SnapLock volume so capacity management should work in automatic mode."
