### ISSUE TITLE
Aggregate Capacity Threshold - Free Space Ratio

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/bluexp-cloud-volumes-ontap#283]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-settings.html

### Page title

Manage capacity settings on a Connector

### Summary

If my understanding is correct, "Aggregate Capacity Threshold - Free Space Ratio" affect the decision to expand aggregate. This is more important than Notification. But manual doesn't mention it. could you please verify it and improve explanation about this parameter ?

I'm reffering this doc :
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage-management.html
BlueXP checks the **free space ratio** every 15 minutes to determine if it needs to purchase additional disks.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi Hayato, thank you for your comment. We are in the process of analyzing it. We will update you once we have a fix and are able to resolve this issue.

**Comment by netapp-ehoffman** [comment]
This issue is being tracked in BLUEXPDOC-82. Closing the GitHub issue.
