### ISSUE TITLE
Capacity Licenses conversion from PayGo to BYOL

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-cloud-volumes-ontap#284]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html

### Page title

Manage capacity-based licenses

### Summary

I know that node based licenses do not support conversion of PayGo to BYOL license model, can we have the same information spelled out here when dealing with capacity based licenses?  I believe it's supported with capacity licenses but it's not clear in the documentation that I can deploy CVO using a Capacity PAYGO license and then add a Capacity BYOL license at a later time.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. We will keep you posted once the updated documentation is available. Please let us know if you have any other feedback.

Thanks again,

Don Riley

**Comment by netapp-bcammett** [comment]
It's kind of described here in a round about way:
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#consumption-models

Specifically this part:

> If you purchase a license from NetApp (BYOL), you also need to subscribe to the PAYGO offering from your cloud provider's marketplace.
> 
> Your license is always charged first, but you'll be charged from the hourly rate in the marketplace in these cases:
> 
>- If you exceed your licensed capacity
> 
> - If the term of your license expires

But it could be expanded upon to clearly state what's supported and describe what happens in the different scenarios (for example, what Jason described: PAYGO first, then BYOL).

Regards,
Ben

**Comment by netapp-driley** [comment]
Hi Jason - I brought this issue up to our Product Manager and was able to confirm that CVO capacity BYOL to PAYGO conversion is no longer supported. It looks like you're an internal NetApp user so I can provide a link to a CVO FAQ that provides additional information on this item if needed. 

Thanks, 

Don
