### ISSUE TITLE
Explanation of "Resize a volume" is obsoleted.

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/bluexp-cloud-volumes-ontap#285]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-volumes.html

### Page title

Manage existing volumes

### Summary

Regarding "Resize a Volume", 
In recent ONTAP,  BlueXP won't switch to system manager screen anymore. Procedure is a bit different than before. We can complete task in Adavanced View. Explanation should be updated.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thank you for your doc change request. We will review this item and update the documentation as requested. We will inform you when the updated documentation is available. Please let us know if you have any other feedback.

--Manini

**Comment by netapp-manini** [comment]
This issue has been resolved: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-volumes.html#resize-a-volume
