### ISSUE TITLE
Feedback on 'Set up IAM roles for Cloud Volumes ONTAP'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-cloud-volumes-ontap#288]
### Summary
 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-iam-roles.html

There is a syntax error in the HA Mediator policy definition. It shows:

{
                "Version": "2012-10-17",
                "Statement": [{
                                                "Effect": "Allow",
                                                "Action": [
                                                                "ec2:AssignPrivateIpAddresses",
                                                                "ec2:CreateRoute",
                                                                "ec2:DeleteRoute",
                                                                "ec2:DescribeNetworkInterfaces",
                                                                "ec2:DescribeRouteTables",
                                                                "ec2:DescribeVpcs",
                                                                "ec2:ReplaceRoute",
                                                                "ec2:UnassignPrivateIpAddresses"
                "sts:AssumeRole"
                "ec2:DescribeSubnets"
                                                ],
                                                "Resource": "*"
                                }
                ]
}

There should be a comma after the next to the last actions:

{
                "Version": "2012-10-17",
                "Statement": [{
                                                "Effect": "Allow",
                                                "Action": [
                                                                "ec2:AssignPrivateIpAddresses",
                                                                "ec2:CreateRoute",
                                                                "ec2:DeleteRoute",
                                                                "ec2:DescribeNetworkInterfaces",
                                                                "ec2:DescribeRouteTables",
                                                                "ec2:DescribeVpcs",
                                                                "ec2:ReplaceRoute",
                                                                "ec2:UnassignPrivateIpAddresses",
"sts:AssumeRole",
"ec2:DescribeSubnets"
                                                ],
                                                "Resource": "*"
                                }
                ]
}

And, interesting enough, when I pasted the contents here, I can see the are spaces, instead of tabs, for the new “actions” that were added that caused the syntax error.

Regards,

Keith

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
This issue has been resolved.
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-iam-roles.html
