### ISSUE TITLE
Clarification request around statement "[...] (EMS) reports the following two events:"

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/bluexp-cloud-volumes-ontap#298]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html#what-to-expect-if-data-loss-occurs

### Page title

Write speed

### Summary

In the section "What to expect if data loss occurs" the following statement is present:
"If data loss occurs due to high write speed, the Event Management System (EMS) reports the following two events:"

There are two events listed for both "Cloud Volumes ONTAP 9.11.0 to 9.11.1" and "Cloud Volumes ONTAP 9.8 to 9.10.1", but only one for "Cloud Volumes ONTAP 9.12.1 or later"

++++++++++++++++
Cloud Volumes ONTAP 9.12.1 or later

NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.

Cloud Volumes ONTAP 9.11.0 to 9.11.1

DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..

Cloud Volumes ONTAP 9.8 to 9.10.1

DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.
When this happens, Cloud Volumes ONTAP should be able to boot up and continue to serve data without user intervention.
++++++++++++++++

The question is would there still be the two EMS messages in 9.12.1?  Asking because customers would like to monitor for all related EMS messages in their 9.12.1, and it isn't clear to me if it has been reduced to just one message, or if the second is missing from that part of the doc.

Thanks for clarifying!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @definitelynotsteve, thanks for your request. We will look into this issue and update you on this thread when it is resolved.

--Manini

**Comment by definitelynotsteve** [comment]
Hello @netapp-manini - I was wondering if you have any updates on this request.  Please advise when you are able.  Thanks!
-Steve

**Comment by netapp-manini** [comment]
hi @definitelynotsteve, this is under discussion with the SME. I will update you once there is a resolution. Alternatively, please send in your queries to decom-ng-doccomments@netapp.com so that we are aware of your email address and can communicate separately.

**Comment by netapp-manini** [comment]
This is being tracked by [BLUEXPDOC-90]. Closing this issue.
