### ISSUE TITLE
Creating additional SVMs from System Manager?

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/bluexp-cloud-volumes-ontap#299]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in Azure

### Summary

Says in our documentation here that BlueXP supports any additional storage VMs that you create from System Manager or the CLI:
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms.html#supported-number-of-storage-vms
But the instructions on this page only mention CLI.  Is is supported to add SVMs through System Manager for CVOs, and if it is supported is there any difference between adding them in CLI vs. System Manager? Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by alexmal98** [comment]
Hey Don!

My customer actually opened a support case because this page of
documentation seems a bit outdated and confusing. I did my own testing and
found that step 3 looks a bit different now, with some errors in the azure
portal after trying to update to Static from Dynamic.

Thanks,
Alex Maldonado

**Comment by netapp-driley** [comment]
This issue is internally tracked via BLUEXPDOC-91. Closing this issue.
