### ISSUE TITLE
Broken link in 'Quick start for Cloud Volumes ONTAP in AWS'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-cloud-volumes-ontap#301]
### Summary

The ‘Launching a Connector from the AWS Marketplace’ link gives a 404 not found error.

Regards,
Jim Wilkerson

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thank you, Chanda, this link will be fixed whenever we release the documents next.

**Comment by netapp-manini** [comment]
This issue has been resolved.
