### ISSUE TITLE
Change of instance type disabled due to high number of disks

### ISSUE THREAD

**Issue by janhavi1596** [NetAppDocs/bluexp-cloud-volumes-ontap#302]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html

### Page title

Change the EC2 instance type for Cloud Volumes ONTAP

### Summary

It is not clear from documentation when we disable the change in instance type for AWS CVO HA

We see there is an attached KB : https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error

However there is a conflict for the information of CVO HA in AWS
Change in instance type is disabled when the **total attached data disks** in CVO HA (sum of disks in both nodes of HA pair) are greater than 18,
But we see  the storage-limit doc ([target instance type supports] link in kB) mentioning the max limit **per node** as 18  :
https://docs.netapp.com/us-en/cloud-volumes-ontap-9121-relnotes/reference-limits-aws.html#limits-for-capacity-based-licensing

Requesting to make the relevant changes in the documentation to clarify whether the number of disks should be considered in total or at the node level when disabling the change of instance type

### Public issues must not contain sensitive information

- [x] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @janhavi1596, thank you for your comment, we will look into it and update this issue when we have a resolution.

**Comment by netapp-manini** [comment]
@janhavi1596, Tracked by [BLUEXPDOC-96]. Closing this one.
