### ISSUE TITLE
Missing iSCSI lif creation steps for HA in Single AZ

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-cloud-volumes-ontap#305]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in AWS

### Summary

Hi team,

    When creating another SVM in AWS CVO HA Single AZ, doesn't it require an iSCSI LIFs for management functions?  The note in step 5 of the HA single AZ section it states "Modifying the services is required because it ensures that Cloud Volumes ONTAP can use the iSCSI LIF for outbound management connections."

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/aws/task-managing-svms-aws.html#create-a-storage-vm-on-an-ha-pair-in-a-single-az

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-manini** [comment]
Tracked by BLUEXPDOC-99.

**Comment by netapp-manini** [comment]
As discussed with @virtualhawk, closing this issue as no changes are required at this time.
