### ISSUE TITLE
Network route command results in error

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-cloud-volumes-ontap#308]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in Azure

### Summary

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap/assets/18287750/611859c4-6e3d-4224-81fa-8049591c99c6)

Customer reported that running the command as specified in the documentation results in the following error: Error: invalid argument “-vserver XYZ”.

Running the command in the following sequence worked: network route create -vserver XYZ -destination 0.0.0.0/0 -gateway 1.2.3.4. This is consistent with documentation on the network route create command: https://docs.netapp.com/us-en/ontap-cli-9141/network-route-create.html#description

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
This feedback came from an email to our doccomments email.

**Comment by netapp-manini** [comment]
Thanks @netapp-bcammett, will soon look into it. Will update this issue when we have a resolution.

**Comment by netapp-manini** [comment]
This has been resolved.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html
