### ISSUE TITLE
More specifics on CVO w/ FlexCache

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/bluexp-cloud-volumes-ontap#311]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-accelerate-data-access.html

### Page title

Accelerate data access with FlexCache volumes

### Summary

Hello! When setting up FlexCache on a CVO system and I think there needs to be more specific documentation on prerequisites for this process, specific to CVO (not just ONTAP).  When creating the FlexCache volume, if the source is encrypted using VE, I believe Azure Key Vault with NVE has to be set up. This prerequisite for using encryption is not clear in ONTAP documentation.  

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @alexmal98, thanks for your suggestion. We will look into it and update this thread when it is resolved. Thanks again.

**Comment by netapp-manini** [comment]
Tracked by BLUEXPDOC-119

**Comment by netapp-manini** [comment]
The doc feedback in this issue has been addressed here: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-accelerate-data-access.html#work-with-flexcache-when-the-origin-is-encrypted
