### ISSUE TITLE
Remove SVM-DR documentation

### ISSUE THREAD

**Issue by scottkntap** [NetAppDocs/bluexp-cloud-volumes-ontap#313]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-svm-dr.html

### Page title

Set up SVM disaster recovery

### Summary

It has come to my attention that SVM-DR in CVO is broken across all 3 clouds.  Can we remove or hide this doc page and references to ONTAP SVM-DR until it (hopefully) gets fixed?  Thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @scottkntap, thank you for pointing this out. We will investigate and close this issue with appropriate messaging.

**Comment by scottkntap** [comment]
Please cancel this request.  On further discussion this is is a miscommunication.

**Comment by netapp-manini** [comment]
Sure. Thanks.
