### ISSUE TITLE
the singular of ellipses is ellipsis, not ellipse

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/bluexp-cloud-volumes-ontap#314]
Believe it or not, I had a reason to be looking at ellipses use across the organization and I ran into this. 

### Files
https://github.com/search?q=repo%3ANetAppDocs%2Fbluexp-cloud-volumes-ontap%20ellipse&type=code

### Reference
https://www.google.com/search?q=what+is+the+singular+of+ellipses

**Comment by ntap-bmegan** [comment]
I should clarify, other sites within NetApp Docs that reference the UI three-dot symbol with a text label use _ellipses_ (plural) not _ellipsis_ (singular). But _ellipse_ refers to the oval shape, not the three dots. 

https://github.com/search?q=%22ellipses%22+user%3ANetAppDocs+%28path%3A*.adoc+OR+path%3A*.yml%29&type=code&ref=advsearch

**Comment by netapp-manini** [comment]
Thank you for adding  this comment. I will fix and release this.

**Comment by netapp-manini** [comment]
Legacy typo fixed.
