### ISSUE TITLE
Add tamperproofed snapshot support for CVO using WORM

### ISSUE THREAD

**Issue by gityrh** [NetAppDocs/bluexp-cloud-volumes-ontap#317]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html

### Page title

WORM storage

### Summary

We can create tamperproof snapshots using WORM by snaplocking them in Azure CVO. It is missing in the documentation, it would be helpful for our customers to add it to clarify it. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @gityrh thank you for your suggestion. We will include this information in the documents and update this issue when resolved.
