### ISSUE TITLE
When creating additional SVMs, a custom network policy is assigned to the NAS LIFs (not default-data-files)

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-cloud-volumes-ontap#319]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in Azure

### Summary

I found a discrepancy in the the default behavior when adding additional SVMs in Azure and how we are modifying the network service policies for CVO 9.11.1 and later (Step 7).

In step 2 (Creating data LIFs:) we do not specify which network service policy to attach to the NAS LIF therefore it attaches a "custom-data-xxxx" policy by default.

In Step 7, we only modify the default-data-files policy by removing the management and data-fpolicy services and adding them to default-data-blocks and default-data-iscsi policies.

Currently, when adding additional SVMs, management traffic will still try to traverse the NAS LIFs due to the management services not being removed from the "custom-data-xxxx" policy.

Possible solutions:
1. Specify the "default-data-files" network service policy when creating the NAS LIFs.
or
2. add removing the management/fpolicy services to the "custom-data-xxxx" policy to Step 7.  
 
This can wildcarded using the following command.
network interface service-policy remove-service -vserver <svm-name> -policy custom-data-* -service data-fpolicy-client
network interface service-policy remove-service -vserver <svm-name> -policy custom-data-* -service management-ad-client
network interface service-policy remove-service -vserver <svm-name> -policy custom-data-* -service management-dns-client
network interface service-policy remove-service -vserver <svm-name> -policy custom-data-* -service management-ldap-client
network interface service-policy remove-service -vserver <svm-name> -policy custom-data-* -service management-nis-client

**Note**
In the AWS steps we specify the "default-data-files" policy when creating the NAS LIF. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html#create-a-storage-vm-on-an-ha-pair-in-a-single-az
*******************

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We will review this item and update the documentation accordingly. If you have any other feedback, please let us know. 

Thanks again for your help, 

Don Riley

**Comment by virtualhawk** [comment]
Hi Don,

                Thank you so much. I have attached screenshots of the default behavior for your reference that Scott Kovacs and I tested in his lab.

The steps in the "Create Storage VMs in AWS" specify the "default-data-files" policy when creating the LIFs, just as an FYI:  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html#create-a-storage-vm-on-an-ha-pair-in-a-single-az

Let me know if you need any additional information.

Thanks,

David Hawkins
Professional Service Consultant
Global Services Solutions Center

NetApp
330.892.7057 Direct Phone
***@***.******@***.***>

[A logo with a white square on it    Description automatically generated with medium confidence]

[A black circle with white letters    Description automatically generated]   [A black and white logo    Description automatically generated]    [A black and white logo    Description automatically generated]    [A black circle with a white play button    Description automatically generated]    [A black circle with white letters in it    Description automatically generated]    [A black circle with white x in it    Description automatically generated]    [A black circle with white logo    Description automatically generated]

"We're committed to providing our customers with the best products and services. Scan the QR code or click on this link<https://listening.netapp.com/jfe/form/SV_3n6lnfKz33d6feC> to provide your feedback. All responses will be anonymous and kept confidential.  Thank you!"

**Comment by netapp-driley** [comment]
This issue has been resolved and the documentation has been updated.

**Comment by virtualhawk** [comment]
Thank you so much Don and team!


Thanks,



David Hawkins

Professional Services Consultant

Global Services Solutions Center



NetApp

3308927057 -  Direct Phone

***@***.******@***.***>



Upcoming Out of the office: None

________________________________
