### ISSUE TITLE
Document should include critical information regarding how the Azure Key Vault heartbeat works

### ISSUE THREAD

**Issue by jpick-66** [NetAppDocs/bluexp-cloud-volumes-ontap#320]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-key-vault.html

### Page title

Manage keys with Azure Key Vault

### Summary

Please reference the information from this internal KB: https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/How_does_the_Azure_Key_Vault_heartbeat_work%3F

Essentially, no where is it publicly documented that there is a non-configurable polling period which occurs every 15 minutes between a CVO node and Azure Key Vault.  After four consecutive failures, volumes will be placed offline.  The only information I could find regarding this behavior was in an internal non-public KB which I cannot share.  I believe this is an important piece of data CVO administrators need to have when setting up NVE/AKV.  This request is to document this behavior in our public CVO documentation so customer's can better understand the consequences (outage) of losing connectivity to the AKV.  Not to mention, this behavior is completely different than how an on-Prem ONTAP cluster works with NVE/external key manager.  I would love to discuss this with the CVO PM, TME, or developer.  Please reach out to me if you have any questions.  Thx.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thank you @jpick-66 for bringing this to our notice. We will look into it and update the documents. We will update this thread after this issue is resolved.

**Comment by netapp-manini** [comment]
A limitation has been added to this topic: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-key-vault.html
