### ISSUE TITLE
dead link to Cloud Volumes ONTAP Release Notes

### ISSUE THREAD

**Issue by sbyosh** [NetAppDocs/bluexp-cloud-volumes-ontap#325]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-planning-your-config-azure.html

### Page title

Plan your Cloud Volumes ONTAP configuration in Azure

### Summary

The "Size your system in Azure" > Virtual machine type link to Cloud Volumes ONTAP Release Notes should point to: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @sbyosh, thank you for pointing this out. We will soon fix the link and update this issue post release.

**Comment by netapp-manini** [comment]
This has been fixed.
