### ISSUE TITLE
More details about configuration backups

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-cloud-volumes-ontap#335]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html

### Page title

Default configuration for Cloud Volumes ONTAP

### Summary

The CVO documentation does not have too much information about CVO configuration backups and I also think is not necessary to deepen into it but at the CVO defaults page (https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#default-setup), information could be improved to make the reader understand the purpose of the config backups.

Here says:
"Cloud Volumes ONTAP sends configuration backups to the Connector using HTTP.
The backups are accessible from http://ipaddress/occm/offboxconfig/ where ipaddress is the IP address of the Connector host."

My impression is that we could provide a reader with a bit of context.

You may need to confirm this with other members but what do you think about this change?

"Cloud Volumes ONTAP sends configuration backups to the Connector using HTTP.
The backups are accessible from http://ipaddress/occm/offboxconfig/ where ipaddress is the IP address of the Connector host.
Refer to ONTAP documentation to know more about Cloud Volumes ONTAP configuration backups: https://docs.netapp.com/us-en/ontap/system-admin/config-backup-file-concept.html"
 
I would prefer to write if the config backups are intended for customer usage or only for NetApp Support members but this decision would need your investigation.

(This feedback is from an internal user via MS Teams.)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thanks, @netapp-bcammett for raising this issue. Will look into this and address the docs as required.

**Comment by netapp-manini** [comment]
This has been verified and addressed here: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html
