### ISSUE TITLE
Package Clarification

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/bluexp-cloud-volumes-ontap#339]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

The packages are not as clearly worded as they could be for Essentials.  I'd suggest a table maybe even but the details are:

NOTE: Licensing is based entirely on the volume type created within the CVO(s)....

Essentials Single Node = Read/Write volumes created on a CVO using ONE ONTAP node only.
Essentials High Availability (HA) = Read/Write volumes using TWO ONTAP nodes that can failover to each other for non-disruptive data access.
Essentials SECONDARY Single Node = Data Protection (DP) type volumes (typically SnapMirror or SnapVault destination volumes that are read-only) created on a CVO using ONE ONTAP node only.
Essentials SECONDARY High Availability (HA) = Data Protection (DP) type volumes (typically SnapMirror or SnapVault destination volumes that are read-only) created on a CVO using TWO ONTAP nodes that can failover to each other for non-disruptive data access.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hello - Thank you so much for your feedback. We will review this item and update the documentation accordingly. We will keep you posted once the updated documentation is published.

Thanks again for your help,

Don Riley
