### ISSUE TITLE
Need to change License Conversion Info

### ISSUE THREAD

**Issue by ElusiveCow** [NetAppDocs/bluexp-cloud-volumes-ontap#340]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

Need to change the ability to convert / transition from Node based to Capacity based license.  Site still says this cannot be done but it now can

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thanks for your suggestion, @ElusiveCow. We will investigate this issue and update this thread with a resolution soon.

**Comment by netapp-manini** [comment]
Hi @ElusiveCow, is this functionality available now, or do you want to say that it will be available in the near future?

**Comment by netapp-manini** [comment]
Hi @ElusiveCow, this will soon be added as a part of planned release activity. However, it is a future enhancement, and we will take it up soon. Till then, closing this issue.
