### ISSUE TITLE
Update licensing docs to reflect Node-based EOA

### ISSUE THREAD

**Issue by kerentraht** [NetAppDocs/bluexp-cloud-volumes-ontap#341]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

The Node-based licensing section includes a statement saying that node licensing is still available for existing customers. Though, but November 11, 2024 this will be changed as CVO Node license will be EOAd by that date. 
Please update the section to reflect the upcoming EOA, including the exceptions that will continue, according to the Node EOA FAQ doc: https://fieldportal.netapp.com/explore/699265?searchbar=%7B%22k%22:%22Node%20EOA%22%7D&popupstate=%7B%22state%22:%22app.viewContent%22,%22srefParams%22:%7B%22source%22:9,%22assetId%22:2667232,%22assetComponentId%22:2660348%7D%7D

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thanks, @kerentraht, for the headsup. I will check with the team about accommodating a future enhancement request and update this ticket on the findings.

**Comment by netapp-manini** [comment]
As discussed with @kerentraht, this will be taken up as a separate engineering request. Closing this issue.
