### ISSUE TITLE
password requirement for Cloud Volumes ONTAP

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/bluexp-cloud-volumes-ontap#343]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-password.html

### Page title

Change the password for Cloud Volumes ONTAP

### Summary

Only one password limitation is mentioned while ONTAP manual mentions four. I suggest to align ONTAP Doc below.
https://docs.netapp.com/us-en/ontap/authentication/change-login-password-task.html

Besides, this expression isn't very clear.  I suggest to use same brief expression as ONTAP manual.
(CVO) The new password must be different than one of the last six passwords that you used.
(ONTAP) It cannot be the same as the last six passwords

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
@hayatokurahashi, thank you for your suggestion. We will investigate and update the docs for this change, and update this thread on resolving this comment.

**Comment by netapp-manini** [comment]
The requested change has been published: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-password.html
