### ISSUE TITLE
Could you please add the purpose of the two EBS disks on Mediator ?

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/bluexp-cloud-volumes-ontap#347]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html

### Page title

Default configuration for Cloud Volumes ONTAP

### Summary

As below description, the customer also wants to know what the two EBS volumes purpose.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html?q=mediator+instance#default-setup

For HA pairs, two st1 EBS volumes for the mediator instance, which are approximately 8 GiB and 4 GiB, and an additional 140 GiB gp3 disk in each node to contain a copy of the root data of the other node.

From the below KB, we can know one is used for root disk and another is used for data disk, it helpful to add this info to the above content.

https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/What_EBS_volumes_are_expected_to_be_attached_to_an_AWS_HA_Mediator_instance

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @Xinwei-Wang. Thanks for your suggestion, we will soon look into it and update the docs. You will see this thread with the updated link.

**Comment by netapp-manini** [comment]
This has been fixed: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html?q=mediator+instance#default-setup

**Comment by Xinwei-Wang** [comment]
[like]  Wang, Xinwei reacted to your message:
________________________________
