### ISSUE TITLE
Example for usage using Essentials Secondary HA to Essentials HA

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-cloud-volumes-ontap#348]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

Wondering if we can get a bit of clarity on the scenario when a user is using Essentials Secondary licensing and the customer experiences a DR event and those DP volumes now become RW - how is CVO licensed?  An explanation of how the licensing adjusts to Essentials PAYGO if an Essentials Primary license is not available or if they do how it would draw from any remaining capacity available in the license would be great.  The example provided in the BYOL section of the document is useful but not as useful as an example to explain this use case (which is pretty common) where the customer is using Essentials Secondary for DR purposes.  Feel free to reach out for clarification.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thank you, @jasonfiset, for drawing our notice to this scenario. We will investigate and add appropriate content to the same topic, and update this topic when this issue is resolved.

**Comment by netapp-manini** [comment]
@jasonfiset, I have included the information here, we are also looking at reorganizing this topic. Stay tuned! 

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#packages
