### ISSUE TITLE
Node-Based Licensing was removed

### ISSUE THREAD

**Issue by wilshields** [NetAppDocs/bluexp-cloud-volumes-ontap#352]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html

### Page title

Cloud Volumes ONTAP licensing

### Summary

There was a section under node-based licensing the link to where customers could download their new NLFs after they purchased/renewed them. That link and information is missing and needs to be returned as we still have use cases where customer need to follow that process. Can you add it back or point me to where it was moved. I think it was just removed but, cannot say for certain.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @wilshields. Thanks for your query. Are you looking for this link: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#obtain-a-system-license-file?

**Comment by wilshields** [comment]
Yes. That’s it. Thank you so much. BlackRock hit an issue with a couple of their HA pairs and I couldn't find this information for them.

v/r --
Wil Shields
US Public Sector Cloud Solutions Architect, CVO Product Team
Mobile Phone: 678.379.3664
Need Help? Please see our SharePoint<https://netapp.sharepoint.com/sites/CloudsolutionarchitectsGroup/SitePages/DetailedEngagementProcess.aspx>


From: Manini Mandal ***@***.***>
Date: Monday, October 21, 2024 at 2:27 AM
To: NetAppDocs/bluexp-cloud-volumes-ontap ***@***.***>
Cc: Shields, Wil ***@***.***>, Mention ***@***.***>
Subject: Re: [NetAppDocs/bluexp-cloud-volumes-ontap] Node-Based Licensing was removed (Issue #352)
EXTERNAL EMAIL - USE CAUTION when clicking links or attachments



Hi @wilshields<https://github.com/wilshields>. Thanks for your query. Are you looking for this link: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#obtain-a-system-license-file?

**Comment by netapp-manini** [comment]
You are welcome...
