### ISSUE TITLE
The details for creating Azure IPs for HA Pair are not clear from the document.

### ISSUE THREAD

**Issue by e175006** [NetAppDocs/bluexp-cloud-volumes-ontap#353]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in Azure

### Summary

Thanks NetApp team for the detailed document you provided.
I have a concern regarding the document structure for HA Pairs.

The document explains the process of creating IPs for the VM of a single node system on Azure. It covers creating an IP address for data LIF / SVM Mgmt access. However, it does not mention that for HA mode, one would need to go to each VM in the cluster and create corresponding IPs under the nic0 on each of the VMs. This part is missing and it would be helpful to include it. As the document progresses to the HA Pair section, it is already mentioned that IPs should be available for each Node.

Additionally, for NFS protocol related configurations, the document states that "The iSCSI LIFs are required for DNS communication." However, it does not mention that one needs to create an iSCSI LIF in addition to a data LIF, even if the iSCSI protocol is not used. It would be beneficial to include this information as well.

Furthermore, it would be helpful if the procedure could include a detail about using the IPs created in Azure (from the top of the procedure) as data LIFs. Perhaps, a reference could be added in the "Create data LIFs" section.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @e175006, thank you for your suggestions. We will look into your concern and address the concern that you have raised. Will update you on the resolution at the earliest.

**Comment by netapp-manini** [comment]
This has been resolved, thanks:

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html#ha-pair
