### ISSUE TITLE
Include the Optimized license

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetAppDocs/bluexp-cloud-volumes-ontap#361]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-licensing-google.html

### Page title

Set up licensing for Cloud Volumes ONTAP in Google Cloud

### Summary

The Capacity-based license [section](https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-licensing-google.html#capacity-based-license) states about two packages: _the Essentials package or the Professional package_. It should include the **Optimized package** too.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thanks, @pablogarciaarevalo, for bringing this up; we will soon rectify this filtering issue and update the topic.

**Comment by netapp-manini** [comment]
This is fixed.
