### ISSUE TITLE
Azure Storage Service Encryption web links are dead

### ISSUE THREAD

**Issue by chuffster80** [NetAppDocs/bluexp-cloud-volumes-ontap#363]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-azure-encryption.html

### Page title

Set up Cloud Volumes ONTAP to use a customer-managed key in Azure

### Summary

Just FYI
https://azure.microsoft.com/en-us/documentation/articles/storage-service-encryption/

this link leads to a 404 Error

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thank you @chuffster80 for reporting this. Looks like the Azure links have been deprecated. We will soon refresh our docs with the updated links and let you know.

**Comment by netapp-manini** [comment]
The links have been fixed.
