### ISSUE TITLE
Cloud you consider to add "What will happen after remove a capacity-based license."

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/bluexp-cloud-volumes-ontap#367]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html

### Page title

Manage capacity-based licenses

### Summary

To whom it may concern,
My customer asked about below in the document.
====================================================================
Remove a capacity-based license
If a capacity-based license expired and is no longer in use, then you can remove it at any time.
====================================================================
They asked me "After remove license, What will happen about our CVO?"
"Is it possible to access data continuously?
"If so How long will the data be accessible?"
"Can the license be removed with the data still in CVO?"
Therefore, Cloud you please add more details about the restrictions and behavior when deleting licenses.

best regards,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Hi @imasafum. We will look into this ask and update the doc as required. Please wait to see this thread updated.

**Comment by netapp-manini** [comment]
Meanwhile, @imasafum, did you check this KB article? [CVO license shows as expired - NetApp Knowledge Base](https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/CVO_license_shows_as_expired)

**Comment by netapp-manini** [comment]
Added a new FAQ KB and added it in this section: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#remove-a-capacity-based-license
