### ISSUE TITLE
inline volume efficiency features

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/bluexp-cloud-volumes-ontap#61]
Page: [What’s new](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html)

Hello Team,

Could you please update the cvo release notes to include mentioning support for Inline efficiency features?

_Default enablement of storage efficiency on new CVO volumes would involve enablement of the following storage efficiency features_

_- Inline compression - Inline 8K compression for new incoming writes would be attempted in container compressed format.
- Inactive data compression scan - 32K Cold data compression scan can be enabled on the volume. This feature is not enabled by default and requires user-intervention to enable. FSx instances also allow this feature from 9.11.1
- Data Compaction
- Inline deduplication - Inline deduplication works at volume level to find any duplicates for the incoming writes.
- Background deduplication - ADS runs as a background operation to identify duplicate blocks.
-_ 

PS. let me know if this info/link is too public facing

BR,
Gabor.

**Comment by netapp-bcammett** [comment]
Hi Gabor,

This is a new Cloud Volumes ONTAP feature, so it was covered in the Cloud Volumes ONTAP Release Notes:
https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html#9-11-1-rc1-7-june-2022

The release notes in the link that you provided are specific to Cloud Manager management of Cloud Volumes ONTAP. 

Thanks,
Ben

**Comment by laagabi** [comment]
Thanks for the swift response Ben!

Apologies for the wrong link. My aim was to raise the doc burt for the cvo release notes.
We have looked over the cvo release notes for 9111 but could only find this bit

***@***.***

There is no mention of inline volume efficiency features here (nor could I find it on previous pages).

Maybe I`m still looking at the wrong page?

Br,
Gabor.

**Comment by netapp-bcammett** [comment]
The 9.11.1 release notes mentions support for TSSE:

> Increased storage efficiency
> 
> Starting with the 9.11.1 release, all new volumes enabled for storage efficiency will include a new compression feature called temperature-sensitive storage efficiency. The previous generation compression feature is no longer used.
> 
> Temperature-sensitive storage efficiency compresses data based on data temperature, or how often the data is used. Cold data, or data that is not used often, is recompressed with a higher compression ratio for increased storage efficiency.

If there's more to it than that, then I would need to check with the product team.

**Comment by laagabi** [comment]
So that's TSEE, what I`m talking about is ISE == Inline Storage Efficiency.

It is mentioned in the TOI
https://confluence.ngage.netapp.com/display/TOI/TSSE+Support+for+CVO+and+FSx+remaining+work


Default enablement of storage efficiency on new CVO volumes would involve enablement of the following storage efficiency features


  *   Inline compression - Inline 8K compression for new incoming writes would be attempted in container compressed format.
  *   Inactive data compression scan - 32K Cold data compression scan can be enabled on the volume. This feature is not enabled by default and requires user-intervention to enable. FSx instances also allow this feature from 9.11.1
  *   Data Compaction

  *   Inline deduplication - Inline deduplication works at volume level to find any duplicates for the incoming writes.
  *   Background deduplication - ADS runs as a background operation to identify duplicate blocks.

Could you please double check and update the docs if these features are already included in 9.11.1?

Thanks,
Gabor.

**Comment by netapp-rlithman** [comment]
This is an ongoing issue. Please leave it open. Thanks.

**Comment by netapp-rlithman** [comment]
We are unable to resolve this issue, so I'm going to close it. Please reach out again if needed.
